#!/bin/sh

echo "Finishing WSJT-X" install
cd build
mkdir build
cd build
cmake -DWSJT_SKIP_MANPAGES=ON -DWSJT_GENERATE_DOCS=OFF ../wsjtx-2.5.4
sudo cmake --build . --target install
sudo reboot

echo "Completing Audio Mapping"
sudo apt-get install pulseaudio pavucontrol mplayer -y
pulseaudio load-module module-null-sink sink_name=Virtual_Sink sink_properties=device.description=Virtual_Sink
pulseaudio -k

echo "Done! with SDR Setup"
